#!/usr/bin/env bash

_vdfplus () {
	local ENCODINGS='ascii base64 hex latin1 ucs2 utf16le utf8'

	compopt -o filenames

	__check_files () {
		local cur_restore="${cur}"
		local IFS=$'\n'

		local file; for file in $(compgen -f "${cur}"); do
			cur="${file}"; _expand

			if test -d "${cur}"; then \
				COMPREPLY=( "${COMPREPLY[@]}" "${file}" )
			elif test -f "${cur}"; then
				if test "$(command -v xdg-mime)"; then \
					local mimetype="$(xdg-mime query filetype "${cur}")"

					if \
						test "${mimetype}" = 'text/plain' \
						|| test "${mimetype}" = 'application/json'
					then
						COMPREPLY=( "${COMPREPLY[@]}" "${file}" )
					fi
				else
					COMPREPLY=( "${COMPREPLY[@]}" "${file}" )
				fi
			fi
		done

		cur="${cur_restore}"
	}
	__check_options () {
		COMPREPLY=(
			"${COMPREPLY[@]}"
			$(compgen -W "$(_parse_help vdfplus --help)" -- "${cur}")
		)
	}

	COMPREPLY=()

	local cur prev
	_get_comp_words_by_ref cur prev

	case "${prev}" in

		( -d \
		| --i \
		| --in \
		| --ind \
		| --inde \
		| --inden \
		| --indent \
		| --indenta \
		| --indentat \
		| --indentati \
		| --indentatio \
		| --indentation \
		| -s \
		| --s \
		| --se \
		| --sep \
		| --sepa \
		| --separ \
		| --separa \
		| --separat \
		| --separato \
		| --separator )
			COMPREPLY=( ${cur:+"${cur}"} )
			;;

		( -e \
		| --e \
		| --en \
		| --enc \
		| --enco \
		| --encod \
		| --encodi \
		| --encodin \
		| --encoding \
		| -o \
		| --o \
		| --ou \
		| --out \
		| --outp \
		| --outpu \
		| --output \
		| --output- \
		| --output-e \
		| --output-en \
		| --output-enc \
		| --output-enco \
		| --output-encod \
		| --output-encodi \
		| --output-encodin \
		| --output-encoding )
			COMPREPLY=( $(compgen -W "${ENCODINGS}" -- "${cur}") )
			;;

		(*)
			case "${cur}" in
				(-*) __check_options ;;
				(*) __check_files ;;
			esac
			;;

	esac

	unset -f __check_files __check_options
} \
&& complete -F _vdfplus vdfplus
